version: '2'

tasks:

  build:
    desc: Build
    deps: [clean]
    cmds:
      - docker-compose up --build -d --force-recreate

  admin:
    desc: Open database browser
    cmds:
      - open -a 'Google Chrome' http://localhost:8081

  clean:
    desc: Clean
    cmds:
      - docker-compose down -v
      - docker rmi backend_postgrest --force
